name: Build, Lint, and Test

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Upload installed dependencies
        uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules/

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download installed dependencies
        uses: actions/download-artifact@v1
        with:
          name: node_modules

      - name: Compile Production Build
        run: yarn build

  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download installed dependencies
        uses: actions/download-artifact@v1
        with:
          name: node_modules

      - name: Run eslint
        run: yarn lint

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download installed dependencies
        uses: actions/download-artifact@v1
        with:
          name: node_modules

      - name: Run Jest
        run: yarn test
